# Generated by Django 2.2.7 on 2020-03-23 17:57

import dataAPI.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerobox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aerobox_id', models.CharField(default=1, max_length=100)),
                ('sitename', models.CharField(default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AeroboxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm', models.FloatField(blank=True)),
                ('temp', models.FloatField(blank=True)),
                ('rh', models.IntegerField(blank=True)),
                ('co2', models.IntegerField(blank=True)),
                ('lon', models.FloatField(blank=True)),
                ('lat', models.FloatField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pj_name', models.CharField(default=1, max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('aerobox', models.ManyToManyField(to='dataAPI.Aerobox')),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(default=1, max_length=100)),
                ('personal_key', models.CharField(blank=True, default=dataAPI.models.create_key, max_length=33, unique=True)),
                ('projectdata', models.ManyToManyField(to='dataAPI.ProjectData')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aerobox',
            name='aeroboxdata',
            field=models.ManyToManyField(to='dataAPI.AeroboxData'),
        ),
    ]
